=== dduponchel/IzPack/izpack-core/src/main/resources/xsd/installation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://izpack.org/xsd/installation"
           targetNamespace="http://izpack.org/xsd/installation" elementFormDefault="qualified"
           attributeFormDefault="unqualified">
    <xs:element name="installation" type="installationType" />
    <xs:complexType name="installationType">
        <xs:all>
            <xs:element name="info" type="infoType" minOccurs="1">
                <xs:annotation>
                    <xs:documentation>The info section</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="guiprefs" type="guiprefsType" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Flexible and in the screen proportions</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="variables" type="variablesType" minOccurs="0" />
            <xs:element name="packaging" type="packagingType" minOccurs="0" />
            <xs:element name="resources" type="resourcesType" minOccurs="0" />
            <xs:element name="locale" type="localeType" minOccurs="1">
                <xs:annotation>
                    <xs:documentation>Locales of the installation</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="panels" type="panelsType" minOccurs="1">
                <xs:annotation>
                    <xs:documentation>The panels in order</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="listeners" type="listenersType" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>The listeners section</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="natives" type="nativesType" minOccurs="0" />
            <xs:element name="packs" type="packsType">
                <xs:annotation>
                    <xs:documentation>The packs section</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
        <xs:attribute name="version" type="xs:string" />
    </xs:complexType>
    <!-- type for info section -->
    <xs:complexType name="authorType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="email" type="xs:string" use="required" />
                <xs:attribute name="name" type="xs:string" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="infoType">
        <xs:sequence>
            <xs:element name="appname" type="xs:string" />
            <xs:element name="appversion" type="xs:string" />
            <xs:element name="appsubpath" minOccurs="0" />
            <xs:element name="authors" type="authorsType" minOccurs="0" />
            <xs:element name="url" type="xs:string" minOccurs="0" />
            <xs:element name="javaversion" type="xs:string" minOccurs="0" />
            <xs:element name="requiresjdk" type="xs:string" minOccurs="0" />
            <xs:element name="pack200" type="xs:string" minOccurs="0" />
            <xs:element name="run-privileged" type="run-privilegedType" minOccurs="0" />
            <xs:element name="summarylogfilepath" type="xs:string" minOccurs="0" />
            <xs:element name="uninstaller" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="write" default="yes">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="yes" />
                                <xs:enumeration value="no" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="name" type="xs:string" default="uninstaller.jar" />
                    <xs:attribute name="condition" type="xs:string" />
                    <xs:attribute name="path" type="xs:string" />
                </xs:complexType>
            </xs:element>
            <xs:element name="writeinstallationinformation" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="yes" />
                        <xs:enumeration value="no" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="run-privilegedType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="condition" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <!-- Variables types -->
    <xs:complexType name="variablesType">
        <xs:sequence>
            <xs:element name="variable" type="variableType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="variableType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="optional" />
                <xs:attribute name="value" type="xs:string" use="optional" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <!-- Variables types -->
    <xs:complexType name="packagingType">
        <xs:sequence>
            <xs:element name="packager" type="packagerType" />
            <xs:element name="unpacker" type="packagerType" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="packagerType">
        <xs:sequence>
            <xs:element name="options">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="packagerOptionsType">
                            <xs:anyAttribute namespace="##any" />
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="class" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="packagerOptionsType">
        <!--TODO : find what goes here-->
    </xs:complexType>
    <!-- Filesets types -->
    <xs:complexType name="filesetType">
        <xs:sequence>
            <xs:element name="include" type="includeType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="exclude" type="includeType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="dir" type="xs:string" use="required" />
        <xs:attribute name="targetdir" type="xs:string" use="required" />
    </xs:complexType>
    <xs:complexType name="includeType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <!-- Resources types -->
    <xs:complexType name="resourcesType">
        <xs:sequence>
            <xs:element name="res" type="resourceType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="resourceType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="src" type="xs:string" use="required" />
                <xs:attribute name="id" type="xs:string" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="packType">
        <xs:sequence>
            <xs:element name="description" type="xs:string" maxOccurs="1" />
            <xs:element name="fileset" type="filesetType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="file" type="fileType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="executable" type="executableType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="required" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="osType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="family" type="xs:string" use="optional" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="langpackType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="iso3" type="xs:string" use="optional" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <!-- Panels definition -->
    <xs:complexType name="panelsType">
        <xs:sequence>
            <xs:element name="panel" type="panelType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="panelType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="classname" type="xs:string" use="optional" />
                <xs:attribute name="id" type="xs:string" use="optional" />
                <xs:attribute name="encoding" type="xs:string" use="optional" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="guiprefsType">
        <xs:sequence>
            <xs:element name="modifier" type="modifierType" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>GUI addaption for more informations see "Modifying the GUI" in the documentation
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="height" type="xs:string" />
        <xs:attribute name="resizable" type="xs:string" />
        <xs:attribute name="width" type="xs:string" />
        <xs:attribute name="splash" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="authorsType">
        <xs:sequence>
            <xs:element name="author" type="authorType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="modifierType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="key" type="xs:string" use="optional" />
                <xs:attribute name="value" type="xs:string" use="optional" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <!-- Listener definition -->
    <xs:complexType name="listenerType" mixed="true">
        <xs:sequence>
            <xs:element name="os" type="osType" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="classname" type="xs:string" use="optional" />
        <xs:attribute name="stage" type="xs:string" use="optional" />
    </xs:complexType>
    <xs:complexType name="listenersType">
        <xs:sequence>
            <xs:element name="listener" type="listenerType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="localeType">
        <xs:sequence>
            <xs:element name="langpack" type="langpackType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="packsType">
        <xs:sequence>
            <xs:element name="pack" type="packType" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>The core files</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="executableType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="targetfile" type="xs:string" use="optional" />
                <xs:attribute name="stage" type="xs:string" use="optional" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="nativesType">
        <xs:sequence>
            <xs:element name="native" type="nativeType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="nativeType">
        <xs:sequence>
            <xs:element name="os" type="osType" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="type" type="xs:string" />
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="stage" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="fileType">
        <xs:sequence>
            <xs:element name="condition" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="os" type="osType" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="src" type="xs:string" use="required" />
        <xs:attribute name="targetdir" type="xs:string" use="required" />
        <xs:attribute name="override" type="xs:boolean" />
        <xs:attribute name="blockable" type="xs:string" />
        <xs:attribute name="unpack" type="xs:boolean" />
    </xs:complexType>
</xs:schema>

=== dduponchel/IzPack/izpack-api/src/test/resources/com/izforge/izpack/api/xml/impl/xinclude/include-expect.xml
<installation version="1.0"
              xmlns:xi="http://www.w3.org/2001/XInclude"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://izpack.org/xsd/installation"
              xsi:schemaLocation="http://izpack.org/xsd/installation ../../../../../../../../../../izpack-core/src/main/resources/org/izpack/xsd/installation.xsd">
    <info>
        <appname>name</appname>
        <appversion>version</appversion>
    </info>
    <packs>
        <pack>
            <description>pack test</description>
        </pack>
        <pack>
            <description>pack test 2</description>
        </pack>
    </packs>
    <panels>
    </panels>
    <locale>
        <langpack iso3="fr" />
    </locale>
</installation>

=== dduponchel/IzPack/izpack-api/src/test/resources/com/izforge/izpack/api/xml/impl/xinclude/multiple-include-input.xml
<installation version="1.0"
              xmlns:xi="http://www.w3.org/2001/XInclude"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://izpack.org/xsd/installation"
              xsi:schemaLocation="http://izpack.org/xsd/installation ../../../../../../../../../../izpack-core/src/main/resources/org/izpack/xsd/installation.xsd">
    <info>
        <appname>name</appname>
        <appversion>version</appversion>
    </info>
    <packs>
        <xi:include href="content-fragment.xml" />
        <xi:include href="content-fragment.xml" />
        <xi:include href="content-fragment.xml" />
    </packs>
    <panels>
    </panels>
    <locale>
        <langpack iso3="fr" />
    </locale>
</installation>

=== dduponchel/IzPack/izpack-core/src/test/resources/com/izforge/izpack/xml/normal.xml
<installation version="1.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://izpack.org/xsd/installation"
              xsi:schemaLocation="http://izpack.org/xsd/installation ../../../../../../../../izpack-core/src/main/resources/xsd/installation.xsd">
    <info>
        <appname>name</appname>
        <appversion>version</appversion>
    </info>
    <packs>
        <pack>
            <description>pack test</description>
        </pack>
    </packs>
    <panels>
    </panels>
    <locale>
        <langpack iso3="fr" />
    </locale>
</installation>

=== dduponchel/IzPack/izpack-core/src/test/resources/com/izforge/izpack/xml/impl/xinclude/fallback-input.xml
<installation version="1.0"
              xmlns:xi="http://www.w3.org/2001/XInclude"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://izpack.org/xsd/installation"
              xsi:schemaLocation="http://izpack.org/xsd/installation ../../../../../../../../../izpack-core/src/main/resources/xsd/installation.xsd">
    <info>
        <appname>name</appname>
        <appversion>version</appversion>
    </info>
    <packs>
        <pack>
            <description>pack test</description>
        </pack>
        <xi:include href="does-not-exist.xml">
            <xi:fallback>
                <pack>
                    <description>pack test 2</description>
                </pack>
            </xi:fallback>
        </xi:include>
    </packs>
    <panels>
    </panels>
    <locale>
        <langpack iso3="fr" />
    </locale>
</installation>

=== dduponchel/IzPack/izpack-api/src/test/resources/com/izforge/izpack/api/xml/impl/xinclude/include-text-expect.xml
<installation version="1.0"
              xmlns:xi="http://www.w3.org/2001/XInclude"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://izpack.org/xsd/installation"
              xsi:schemaLocation="http://izpack.org/xsd/installation ../../../../../../../../../../izpack-core/src/main/resources/org/izpack/lxsd/installation.xsd">
    <info>
        <appname>name</appname>
        <appversion>version</appversion>
    </info>
    <packs>
        <pack>
            <description>
                This is some sample text that should be included
            </description>
        </pack>
    </packs>
    <panels>
    </panels>
    <locale>
        <langpack iso3="fr" />
    </locale>
</installation>
